"""Build the public demo from code-only fixtures. Never reads config or usage files."""
import json
import math
import shutil
import hashlib
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def synthetic_data():
    rows = []
    session_rows = []
    names = ('Atlas Code', 'Cedar Think', 'Orbit Local')
    for day in range(90):
        current = date(2026, 1, 1) + timedelta(days=day)
        leader = current.month - 1
        for index, model in enumerate(names):
            wave = 1 + .22 * math.sin(day * .41 + index) + .13 * math.cos(day * .83)
            tokens = round((120000 + day * 1600) * wave * (2.4 if index == leader else 1))
            # Fictional display values, not real model prices or recorded charges.
            cost = round(tokens / 1000000 * (2.8, 4.2, .4)[index], 4)
            rows.append(dict(date=current.isoformat(), host=('workstation', 'lab')[index % 2],
                             app=('Codex', 'Claude Code', 'Codex')[index], model=model,
                             tokens=tokens, requests=12 + day % 17 + index * 4,
                             cost_usd=f'{cost:.4f}'))
            # A fictional session spans up to ten days and can switch models.
            # Some days deliberately lack session detail to demonstrate coverage.
            if day % 11:
                session_rows.append(dict(rows[-1], session_key=hashlib.sha256(f'fictional-session-{day // 10}'.encode()).hexdigest(),
                                         session_title=('Build a sample dashboard', 'Review a fictional API', 'Explore a demo dataset')[day // 10 % 3] + f' · iteration {day // 10 + 1}',
                                         fresh_input_tokens=tokens//4, cache_read_tokens=tokens//2,
                                         cache_creation_tokens=tokens//10,
                                         output_tokens=tokens-tokens//4-tokens//2-tokens//10))
    return dict(generated_at='2026-04-01T00:00:00Z', rows=rows, session_rows=session_rows,
                sources={name: dict(collected_at='2026-04-01T00:00:00Z', timezone='UTC')
                         for name in ('workstation', 'lab')},
                caveats=['All values and model/source names are deterministic fictional examples generated by build_demo.py.',
                         'Demo costs are invented, not pricing guidance. The real dashboard uses CC-Switch recorded estimates.',
                         'Monthly labels show the selected month’s top model by tokens and that model’s cost.',
                         'Animation only reveals existing marks; it does not simulate data collection.'])


def build():
    destination = ROOT / 'docs'
    destination.mkdir(exist_ok=True)
    page = (ROOT / 'web.html').read_text()
    page = page.replace('<title>Token usage</title>', '<title>TokenScope · Synthetic Demo</title>')
    page = page.replace('href="/web.css"', 'href="web.css"')
    page = page.replace('src="/session_usage.js"', 'src="session_usage.js"')
    page = page.replace('<script defer src="/web.js"></script>',
                        '<link rel="stylesheet" href="demo.css"><script defer src="demo-data.js"></script><script defer src="web.js"></script>')
    page = page.replace('<body><main>', '<body><main><nav class="demo-nav"><a href="https://github.com/Crear12/tokenscope">◈ TokenScope</a><span class="demo-badge">SYNTHETIC DEMO</span><a href="https://github.com/Crear12/tokenscope#quick-start">Get the code ↗</a></nav>')
    page = page.replace('<h1>Token usage</h1>', '<p class="eyebrow">YOUR MODELS. ONE CLEAR VIEW.</p><h1>Tokens tell a story.<br>See the whole picture.</h1>')
    page = page.replace('id="show-sessions" type="checkbox"', 'id="show-sessions" type="checkbox" checked')
    page = page.replace('<div class="actions"><label>Refresh every', '<div class="actions live-controls" hidden><label>Refresh every', 1)
    page = page.replace('</header>', '<div class="demo-actions"><button id="replay">↻ Replay animation</button><a href="https://github.com/Crear12/tokenscope">View on GitHub ↗</a></div></header>', 1)
    page = page.replace('LAN viewers can change the shared refresh interval. Date and model filters affect only your browser. No requests overlap; refreshes run at clock-aligned boundaries while this command is running.',
                        'TokenScope · MIT licensed · This public demo contains no real usage. All interactions run in your browser. Animation respects reduced-motion preferences. Run the Python app locally to collect your own statistics.')
    (destination / 'index.html').write_text(page)
    (destination / 'demo-data.js').write_text('window.TOKEN_SCOPE_DEMO = ' + json.dumps(synthetic_data(), separators=(',', ':')) + ';\n')
    for name in ('web.js', 'web.css', 'session_usage.js'):
        shutil.copyfile(ROOT / name, destination / name)
    (destination / '.nojekyll').touch()
    print('Built docs/ from synthetic fixtures only.')


if __name__ == '__main__':
    build()
